name: Run Initial Test - at the moment "Main Runner"

on:
  push:
    branches:
      - development

  workflow_dispatch:

jobs:
  Selenium_Tests:
    runs-on: windows-latest

    steps:
      # Code checkout
      - name: Check Out Code
        uses: actions/checkout@v4

      # JDK installation
      - name: JDK installation
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: "temurin"

      #Bild project
      - name: BUILD project
        run: mvn clean install

      - name: Target file
        uses: actions/upload-artifacts@V3
        with:
          name: target-file
          path:
            target

      #Run Tests
      - name: Test RUN
        run: mvn test







